name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag atom:latest
    - name: Run the built Docker image
      run: docker run -i --rm atom --version | grep 'Atom' || false
